version: '3.4'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Info2010
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: Info2010
      ME_CONFIG_MONGODB_URL: mongodb://admin:Info2010@mongo:27017/

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Info2010
      POSTGRES_DB: DiscountDb
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: to_andata@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: Info2010
    volumes:
      - pgadmin_data:/root/.pgadmin

  portainer:
    image: portainer/portainer-ce
    restart: always
    ports:
      - 8080:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    user: root
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: Info2010
      ACCEPT_EULA: Y
      TZ: Asia/Bangkok
    volumes:
      - mssql_data:/var/opt/mssql/data
      - mssql_log:/var/opt/mssql/log

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      node.name: es-node-1
      discovery.type: single-node
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: -Xms256m -Xmx256m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    restart: always
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: Admin
      RABBITMQ_DEFAULT_PASS: Info2010

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data:
  portainer_data:
  mssql_data:
  mssql_log:
  elasticsearch-data:
