version: '3.4'

services:

  catalog.api:
    container_name: catalogapi.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
      #- "ElasticConfiguration:Uri=http://elasticsearch:9200"
    ports:
      - "8000:80"

  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - catalog.api
      #- basket.api
      #- discount.api
      #- ordering.api
    ports:
      - "8010:80"